### ISSUE TITLE
LittleFS write/erase cycle

### ISSUE THREAD

**Issue by andyCLY** [Think-N-Kreate-Ltd/AGIS-Longevity-Tester-firmware#10]
It is known that all FS have a limited write/erase cycle.
Here are some bg info for LittleFS:
+ 10k-100k write/erase cycle
+ 4096 bytes flash block
+ write to different file can use the same block <- not sure

Here is the problem. The original program write to file whenever touch the LS. Assume we do the testing in default value, there is 13 times write within 30 sec. That is, it will write 100k times after run 64.1 hrs.

**Comment by andyCLY** [comment]
## update for info:
To save internal memory, the component has two additional modes which both use sectors of 512 bytes:
+ Performance mode. Erase sector operation data is stored in RAM, the sector is erased, and then data is copied back to flash memory. However, if a device is powered off for any reason, all 4096 bytes of data is lost.
+ Safety mode. The data is first saved to flash memory, and after the sector is erased, the data is saved back. If a device is powered off, the data can be recovered as soon as the device boots up.

The default settings are as follows:
+ Sector size is 512 bytes
+ Performance mode

Change to safety mode also cannot solve the power failure of write problem. Solving that problem does take time. Thus, it will not be solved in this issue. Please do not try any cut-off power for testing.

**Comment by andyCLY** [comment]
## Update: solve method
+ originally, new file init will write a file and append twice -> now: use 1 string to store all and write once only
+ create a new function to 
    1. store the data that want to log
    2. log the data when length > 3900 (as 1 block should <4096)
    3. also do logging when finish
+ not to log data until data length >3900

**Comment by andyCLY** [comment]
## result:
use default value to run testing
+ init cycle 3->1
+ 4min35s cycle+1 (128->1)
+ the last data can also be logged
+ not problem discovered
To conclude:
+ the write/erase cycle reduce a lot
+ where this number is possible to run the test for more than a month non-stop

**Comment by tranvnhan** [comment]
> ## result:
> use default value to run testing
> 
> * init cycle 3->1
> * 4min35s cycle+1 (128->1) (73/89/84,55ms)
> * the last data can also be logged
> * not problem discovered
>   To conclude:
> * the write/erase cycle reduce a lot
> * where this number is possible to run the test for more than a month non-stop

Could it be more specific, "more than a month non-stop"? The Tester will be required to run for at least 2 months. Can it run for 2 months or more?
